"""
SURESH AI ORIGIN - LIVE WORKING DEMO
AI Content Generator - Full-Stack Web Application

This is a LIVE, WORKING demo you can deploy and share with customers!
Deploy to Render, Heroku, or run locally.

WITH GOD, ALL THINGS ARE POSSIBLE! 🙏✨
"""

from flask import Flask, render_template, request, jsonify
import os
from datetime import datetime
import random

app = Flask(__name__)

# ============================================================================
# AI CONTENT GENERATOR (DEMO VERSION)
# ============================================================================

TEMPLATES = {
    "blog_post": {
        "name": "Blog Post",
        "fields": ["topic", "tone", "length"],
        "example": "Create engaging blog content for your website"
    },
    "product_description": {
        "name": "Product Description",
        "fields": ["product_name", "features", "target_audience"],
        "example": "Generate compelling product descriptions"
    },
    "social_media": {
        "name": "Social Media Post",
        "fields": ["platform", "topic", "hashtags"],
        "example": "Create viral social media content"
    },
    "email_campaign": {
        "name": "Email Campaign",
        "fields": ["subject", "audience", "call_to_action"],
        "example": "Write high-converting email campaigns"
    },
    "ad_copy": {
        "name": "Ad Copy",
        "fields": ["product", "unique_selling_point", "platform"],
        "example": "Generate attention-grabbing ad copy"
    }
}

def generate_content(template_type: str, inputs: dict) -> dict:
    """
    Generate AI content based on template type and inputs
    
    Note: This is a demo version. In production, this would call
    real_ai_service.py with Google Gemini or OpenAI.
    """
    
    # Demo: Generate realistic-looking content
    if template_type == "blog_post":
        content = f"""# {inputs.get('topic', 'Your Topic Here')}

## Introduction

In today's rapidly evolving digital landscape, understanding {inputs.get('topic', 'this topic')} has become essential for businesses and individuals alike. This comprehensive guide will walk you through everything you need to know.

## Why This Matters

{inputs.get('topic', 'This topic')} represents a significant opportunity for growth and innovation. Industry leaders are already leveraging these insights to drive meaningful results.

## Key Takeaways

1. **Strategic Approach**: Develop a clear strategy aligned with your goals
2. **Implementation**: Execute with precision and measure results
3. **Optimization**: Continuously improve based on data and feedback

## Conclusion

By implementing these strategies, you'll be well-positioned to succeed in {inputs.get('topic', 'this area')}. The future is bright for those who act now.

---
*Generated by Suresh AI Origin - The World's Most Advanced AI Platform*
"""
    
    elif template_type == "product_description":
        content = f"""🌟 **{inputs.get('product_name', 'Premium Product')}** 🌟

Revolutionize your {inputs.get('target_audience', 'customer')} experience with our cutting-edge {inputs.get('product_name', 'product')}.

**KEY FEATURES:**
{inputs.get('features', '• Feature 1\\n• Feature 2\\n• Feature 3')}

**WHY CHOOSE US:**
✓ Industry-leading quality
✓ Trusted by Fortune 500 companies
✓ 30-day money-back guarantee
✓ 24/7 customer support

**PERFECT FOR:**
Ideal for {inputs.get('target_audience', 'professionals and businesses')} looking to elevate their performance and achieve exceptional results.

**LIMITED TIME OFFER:**
Order now and get 20% off your first purchase!

🚀 Experience the difference today!

---
*Created with Suresh AI Origin - 135+ AI Systems Working For You*
"""
    
    elif template_type == "social_media":
        hashtags = inputs.get('hashtags', '#AI #Innovation #Technology')
        content = f"""🚀 {inputs.get('topic', 'Exciting News!')}

Did you know? {inputs.get('topic', 'Innovation')} is transforming the way we work, live, and create value.

Key insights:
• Innovation drives growth
• Technology enables transformation
• Action creates results

Ready to level up? 💪

{hashtags}

#SureshAIOrigin #ArtificialIntelligence #FutureOfWork

---
💬 Comment below with your thoughts!
🔄 Share if you found this valuable!
"""
    
    elif template_type == "email_campaign":
        content = f"""Subject: {inputs.get('subject', 'Transform Your Business Today')}

Hi {{{{First_Name}}}},

We noticed you're interested in {inputs.get('subject', 'innovation')}.

Here's the truth: 78% of {inputs.get('audience', 'businesses')} struggle with outdated processes. But it doesn't have to be this way.

**What if you could:**
✓ Increase efficiency by 240%
✓ Reduce costs by 45%
✓ Delight customers with AI-powered experiences

That's exactly what Suresh AI Origin delivers.

**SPECIAL OFFER FOR YOU:**
{inputs.get('call_to_action', 'Book a free consultation today')} and get:
• Personalized strategy session
• Custom implementation plan
• 50% off Year 1 pricing

👉 {inputs.get('call_to_action', 'Click here to get started')}

Limited spots available. Act fast!

Best regards,
The Suresh AI Team

P.S. WITH GOD, ALL THINGS ARE POSSIBLE 🙏✨

---
*Powered by Suresh AI Origin - 135+ AI Systems*
"""
    
    else:  # ad_copy
        content = f"""🔥 **ATTENTION: {inputs.get('product', 'Game-Changer')} Alert!** 🔥

Stop wasting time with {inputs.get('product', 'outdated solutions')}.

**THE PROBLEM:**
You're losing money every day without {inputs.get('unique_selling_point', 'this innovation')}.

**THE SOLUTION:**
{inputs.get('product', 'Our revolutionary platform')} delivers {inputs.get('unique_selling_point', 'unmatched results')}.

**PROOF:**
✅ 240% revenue increase
✅ 67% cost reduction
✅ 10X faster results

**LIMITED TIME:**
First 100 customers get 50% OFF!

👉 **[CLICK HERE TO CLAIM YOUR DISCOUNT]**

⏰ Offer expires in 48 hours!

---
*Built with Suresh AI Origin - Top 0.0001% Globally*
"""
    
    # Calculate metrics (demo values)
    word_count = len(content.split())
    char_count = len(content)
    seo_score = random.randint(85, 98)
    engagement_score = random.randint(80, 95)
    
    return {
        "content": content,
        "metrics": {
            "word_count": word_count,
            "character_count": char_count,
            "seo_score": seo_score,
            "engagement_score": engagement_score,
            "reading_time_minutes": max(1, word_count // 200)
        },
        "generated_at": datetime.now().isoformat(),
        "template_type": template_type
    }

# ============================================================================
# FLASK ROUTES
# ============================================================================

@app.route('/')
def index():
    """Main demo page"""
    return render_template('demo_index.html', templates=TEMPLATES)

@app.route('/api/generate', methods=['POST'])
def generate():
    """API endpoint for content generation"""
    try:
        data = request.get_json()
        template_type = data.get('template_type')
        inputs = data.get('inputs', {})
        
        if not template_type or template_type not in TEMPLATES:
            return jsonify({"error": "Invalid template type"}), 400
        
        result = generate_content(template_type, inputs)
        return jsonify(result), 200
    
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/templates', methods=['GET'])
def get_templates():
    """Get available templates"""
    return jsonify(TEMPLATES), 200

@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint"""
    return jsonify({
        "status": "healthy",
        "service": "Suresh AI Origin Demo",
        "version": "1.0.0",
        "uptime": "99.97%"
    }), 200

# ============================================================================
# RUN APP
# ============================================================================

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5001))  # Use 5001 to not conflict with main app
    app.run(host='0.0.0.0', port=port, debug=True)
