"""initial

Revision ID: 6cd71ca07a84
Revises: 
Create Date: 2026-01-10 20:50:12.749285
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6cd71ca07a84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('orders', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('orders', 'receipt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('orders', 'product',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('orders', 'paid_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_orders_product'), 'orders', ['product'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.alter_column('payments', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('payments', 'order_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('payments', 'received_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.alter_column('webhooks', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('webhooks', 'event',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('webhooks', 'received_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_webhooks_event'), 'webhooks', ['event'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_event'), table_name='webhooks')
    op.alter_column('webhooks', 'received_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('webhooks', 'event',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('webhooks', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.alter_column('payments', 'received_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('payments', 'order_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_product'), table_name='orders')
    op.alter_column('orders', 'paid_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'product',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'receipt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
