"""add stripe models and fields

Revision ID: a27bd4c9f5a9
Revises: 30e907a211d8
Create Date: 2026-01-12 11:33:46.663996
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a27bd4c9f5a9'
down_revision = '30e907a211d8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.Float(), nullable=True),
    sa.Column('received_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_events_event_type'), 'stripe_events', ['event_type'], unique=False)
    op.create_table('usage_meters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('receipt', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('attribution_runs', sa.Integer(), nullable=True),
    sa.Column('models_used', sa.Integer(), nullable=True),
    sa.Column('exports', sa.Integer(), nullable=True),
    sa.Column('lookback_days', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Float(), nullable=True),
    sa.Column('period_end', sa.Float(), nullable=True),
    sa.Column('reset_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_meters_receipt'), 'usage_meters', ['receipt'], unique=False)
    op.create_index(op.f('ix_usage_meters_subscription_id'), 'usage_meters', ['subscription_id'], unique=False)
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.alter_column('orders', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('orders', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('orders', 'receipt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('orders', 'product',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('orders', 'paid_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_orders_product'), 'orders', ['product'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.alter_column('payments', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('payments', 'order_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('payments', 'received_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.add_column('subscriptions', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_subscriptions_razorpay_subscription_id'), 'subscriptions', ['razorpay_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.alter_column('webhooks', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('webhooks', 'event',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('webhooks', 'received_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_webhooks_event'), 'webhooks', ['event'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_event'), table_name='webhooks')
    op.alter_column('webhooks', 'received_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('webhooks', 'event',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('webhooks', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_razorpay_subscription_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'razorpay_subscription_id')
    op.drop_column('subscriptions', 'stripe_customer_id')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('subscriptions', 'provider')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.alter_column('payments', 'received_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('payments', 'order_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_product'), table_name='orders')
    op.alter_column('orders', 'paid_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'product',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'receipt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.create_table('campaigns',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('campaign_type', sa.VARCHAR(), nullable=True),
    sa.Column('target_segment', sa.VARCHAR(), nullable=True),
    sa.Column('template_id', sa.VARCHAR(), nullable=True),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('scheduled_at', sa.FLOAT(), nullable=True),
    sa.Column('sent_at', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.FLOAT(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(), nullable=True),
    sa.Column('sent_count', sa.INTEGER(), nullable=True),
    sa.Column('opened_count', sa.INTEGER(), nullable=True),
    sa.Column('clicked_count', sa.INTEGER(), nullable=True),
    sa.Column('converted_count', sa.INTEGER(), nullable=True),
    sa.Column('revenue_generated', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    op.drop_index(op.f('ix_usage_meters_subscription_id'), table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_receipt'), table_name='usage_meters')
    op.drop_table('usage_meters')
    op.drop_index(op.f('ix_stripe_events_event_type'), table_name='stripe_events')
    op.drop_table('stripe_events')
    # ### end Alembic commands ###
