"""add_execution_intelligence_tables

Revision ID: d27fa85d1bf4
Revises: a27bd4c9f5a9
Create Date: 2026-01-12 12:29:54.046276
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd27fa85d1bf4'
down_revision = 'a27bd4c9f5a9'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('skill_level', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_country'), 'user_profiles', ['country'], unique=False)
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_user_profiles_market'), 'user_profiles', ['market'], unique=False)
    op.create_table('workflow_performance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('skill_level', sa.String(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_outcome_value', sa.Float(), nullable=True),
    sa.Column('completion_time_hours', sa.Float(), nullable=True),
    sa.Column('data_points', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_performance_market'), 'workflow_performance', ['market'], unique=False)
    op.create_index(op.f('ix_workflow_performance_skill_level'), 'workflow_performance', ['skill_level'], unique=False)
    op.create_index(op.f('ix_workflow_performance_workflow_name'), 'workflow_performance', ['workflow_name'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('workflow_name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('clicked', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendations_workflow_name'), 'recommendations', ['workflow_name'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('workflow_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.Column('execution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_user_id'), 'workflow_executions', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_name'), 'workflow_executions', ['workflow_name'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('metric_type', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('proof_type', sa.String(), nullable=True),
    sa.Column('proof_url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_execution_id'), 'outcomes', ['execution_id'], unique=False)
    op.create_index(op.f('ix_outcomes_metric_type'), 'outcomes', ['metric_type'], unique=False)
    op.create_index(op.f('ix_outcomes_user_id'), 'outcomes', ['user_id'], unique=False)
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('campaign_type', sa.VARCHAR(), nullable=True),
    sa.Column('target_segment', sa.VARCHAR(), nullable=True),
    sa.Column('template_id', sa.VARCHAR(), nullable=True),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('scheduled_at', sa.FLOAT(), nullable=True),
    sa.Column('sent_at', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.FLOAT(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(), nullable=True),
    sa.Column('sent_count', sa.INTEGER(), nullable=True),
    sa.Column('opened_count', sa.INTEGER(), nullable=True),
    sa.Column('clicked_count', sa.INTEGER(), nullable=True),
    sa.Column('converted_count', sa.INTEGER(), nullable=True),
    sa.Column('revenue_generated', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    op.drop_index(op.f('ix_outcomes_user_id'), table_name='outcomes')
    op.drop_index(op.f('ix_outcomes_metric_type'), table_name='outcomes')
    op.drop_index(op.f('ix_outcomes_execution_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_workflow_executions_workflow_name'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_user_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_recommendations_workflow_name'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_workflow_performance_workflow_name'), table_name='workflow_performance')
    op.drop_index(op.f('ix_workflow_performance_skill_level'), table_name='workflow_performance')
    op.drop_index(op.f('ix_workflow_performance_market'), table_name='workflow_performance')
    op.drop_table('workflow_performance')
    op.drop_index(op.f('ix_user_profiles_market'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_country'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
